// flow-typed signature: 4fc5b93f457262c48086d4adf97e83e9
// flow-typed version: <<STUB>>/jquery.tipsy_v^1.0.3/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jquery.tipsy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jquery.tipsy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jquery.tipsy/src/jquery.tipsy' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jquery.tipsy/src/jquery.tipsy.js' {
  declare module.exports: $Exports<'jquery.tipsy/src/jquery.tipsy'>;
}
