// flow-typed signature: a7b649be5a3e10d5118769987ac6c369
// flow-typed version: <<STUB>>/pnotify_v^4.0.0-alpha.4/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pnotify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pnotify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pnotify/dist/es/PNotify' {
  declare module.exports: any;
}

declare module 'pnotify/dist/es/PNotifyAnimate' {
  declare module.exports: any;
}

declare module 'pnotify/dist/es/PNotifyButtons' {
  declare module.exports: any;
}

declare module 'pnotify/dist/es/PNotifyCallbacks' {
  declare module.exports: any;
}

declare module 'pnotify/dist/es/PNotifyCompat' {
  declare module.exports: any;
}

declare module 'pnotify/dist/es/PNotifyConfirm' {
  declare module.exports: any;
}

declare module 'pnotify/dist/es/PNotifyDesktop' {
  declare module.exports: any;
}

declare module 'pnotify/dist/es/PNotifyHistory' {
  declare module.exports: any;
}

declare module 'pnotify/dist/es/PNotifyMobile' {
  declare module.exports: any;
}

declare module 'pnotify/dist/es/PNotifyNonBlock' {
  declare module.exports: any;
}

declare module 'pnotify/dist/es/PNotifyReference' {
  declare module.exports: any;
}

declare module 'pnotify/dist/es/PNotifyStyleMaterial' {
  declare module.exports: any;
}

declare module 'pnotify/dist/iife/PNotify' {
  declare module.exports: any;
}

declare module 'pnotify/dist/iife/PNotifyAnimate' {
  declare module.exports: any;
}

declare module 'pnotify/dist/iife/PNotifyButtons' {
  declare module.exports: any;
}

declare module 'pnotify/dist/iife/PNotifyCallbacks' {
  declare module.exports: any;
}

declare module 'pnotify/dist/iife/PNotifyCompat' {
  declare module.exports: any;
}

declare module 'pnotify/dist/iife/PNotifyConfirm' {
  declare module.exports: any;
}

declare module 'pnotify/dist/iife/PNotifyDesktop' {
  declare module.exports: any;
}

declare module 'pnotify/dist/iife/PNotifyHistory' {
  declare module.exports: any;
}

declare module 'pnotify/dist/iife/PNotifyMobile' {
  declare module.exports: any;
}

declare module 'pnotify/dist/iife/PNotifyNonBlock' {
  declare module.exports: any;
}

declare module 'pnotify/dist/iife/PNotifyReference' {
  declare module.exports: any;
}

declare module 'pnotify/dist/iife/PNotifyStyleMaterial' {
  declare module.exports: any;
}

declare module 'pnotify/dist/umd/PNotify' {
  declare module.exports: any;
}

declare module 'pnotify/dist/umd/PNotifyAnimate' {
  declare module.exports: any;
}

declare module 'pnotify/dist/umd/PNotifyButtons' {
  declare module.exports: any;
}

declare module 'pnotify/dist/umd/PNotifyCallbacks' {
  declare module.exports: any;
}

declare module 'pnotify/dist/umd/PNotifyCompat' {
  declare module.exports: any;
}

declare module 'pnotify/dist/umd/PNotifyConfirm' {
  declare module.exports: any;
}

declare module 'pnotify/dist/umd/PNotifyDesktop' {
  declare module.exports: any;
}

declare module 'pnotify/dist/umd/PNotifyHistory' {
  declare module.exports: any;
}

declare module 'pnotify/dist/umd/PNotifyMobile' {
  declare module.exports: any;
}

declare module 'pnotify/dist/umd/PNotifyNonBlock' {
  declare module.exports: any;
}

declare module 'pnotify/dist/umd/PNotifyReference' {
  declare module.exports: any;
}

declare module 'pnotify/dist/umd/PNotifyStyleMaterial' {
  declare module.exports: any;
}

declare module 'pnotify/lib/es/PNotify' {
  declare module.exports: any;
}

declare module 'pnotify/lib/es/PNotifyAnimate' {
  declare module.exports: any;
}

declare module 'pnotify/lib/es/PNotifyButtons' {
  declare module.exports: any;
}

declare module 'pnotify/lib/es/PNotifyCallbacks' {
  declare module.exports: any;
}

declare module 'pnotify/lib/es/PNotifyCompat' {
  declare module.exports: any;
}

declare module 'pnotify/lib/es/PNotifyConfirm' {
  declare module.exports: any;
}

declare module 'pnotify/lib/es/PNotifyDesktop' {
  declare module.exports: any;
}

declare module 'pnotify/lib/es/PNotifyHistory' {
  declare module.exports: any;
}

declare module 'pnotify/lib/es/PNotifyMobile' {
  declare module.exports: any;
}

declare module 'pnotify/lib/es/PNotifyNonBlock' {
  declare module.exports: any;
}

declare module 'pnotify/lib/es/PNotifyReference' {
  declare module.exports: any;
}

declare module 'pnotify/lib/es/PNotifyStyleMaterial' {
  declare module.exports: any;
}

declare module 'pnotify/lib/iife/PNotify' {
  declare module.exports: any;
}

declare module 'pnotify/lib/iife/PNotifyAnimate' {
  declare module.exports: any;
}

declare module 'pnotify/lib/iife/PNotifyButtons' {
  declare module.exports: any;
}

declare module 'pnotify/lib/iife/PNotifyCallbacks' {
  declare module.exports: any;
}

declare module 'pnotify/lib/iife/PNotifyCompat' {
  declare module.exports: any;
}

declare module 'pnotify/lib/iife/PNotifyConfirm' {
  declare module.exports: any;
}

declare module 'pnotify/lib/iife/PNotifyDesktop' {
  declare module.exports: any;
}

declare module 'pnotify/lib/iife/PNotifyHistory' {
  declare module.exports: any;
}

declare module 'pnotify/lib/iife/PNotifyMobile' {
  declare module.exports: any;
}

declare module 'pnotify/lib/iife/PNotifyNonBlock' {
  declare module.exports: any;
}

declare module 'pnotify/lib/iife/PNotifyReference' {
  declare module.exports: any;
}

declare module 'pnotify/lib/iife/PNotifyStyleMaterial' {
  declare module.exports: any;
}

declare module 'pnotify/lib/umd/PNotify' {
  declare module.exports: any;
}

declare module 'pnotify/lib/umd/PNotifyAnimate' {
  declare module.exports: any;
}

declare module 'pnotify/lib/umd/PNotifyButtons' {
  declare module.exports: any;
}

declare module 'pnotify/lib/umd/PNotifyCallbacks' {
  declare module.exports: any;
}

declare module 'pnotify/lib/umd/PNotifyCompat' {
  declare module.exports: any;
}

declare module 'pnotify/lib/umd/PNotifyConfirm' {
  declare module.exports: any;
}

declare module 'pnotify/lib/umd/PNotifyDesktop' {
  declare module.exports: any;
}

declare module 'pnotify/lib/umd/PNotifyHistory' {
  declare module.exports: any;
}

declare module 'pnotify/lib/umd/PNotifyMobile' {
  declare module.exports: any;
}

declare module 'pnotify/lib/umd/PNotifyNonBlock' {
  declare module.exports: any;
}

declare module 'pnotify/lib/umd/PNotifyReference' {
  declare module.exports: any;
}

declare module 'pnotify/lib/umd/PNotifyStyleMaterial' {
  declare module.exports: any;
}

declare module 'pnotify/make' {
  declare module.exports: any;
}

declare module 'pnotify/src/PNotifyCompat' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pnotify/dist/es/PNotify.js' {
  declare module.exports: $Exports<'pnotify/dist/es/PNotify'>;
}
declare module 'pnotify/dist/es/PNotifyAnimate.js' {
  declare module.exports: $Exports<'pnotify/dist/es/PNotifyAnimate'>;
}
declare module 'pnotify/dist/es/PNotifyButtons.js' {
  declare module.exports: $Exports<'pnotify/dist/es/PNotifyButtons'>;
}
declare module 'pnotify/dist/es/PNotifyCallbacks.js' {
  declare module.exports: $Exports<'pnotify/dist/es/PNotifyCallbacks'>;
}
declare module 'pnotify/dist/es/PNotifyCompat.js' {
  declare module.exports: $Exports<'pnotify/dist/es/PNotifyCompat'>;
}
declare module 'pnotify/dist/es/PNotifyConfirm.js' {
  declare module.exports: $Exports<'pnotify/dist/es/PNotifyConfirm'>;
}
declare module 'pnotify/dist/es/PNotifyDesktop.js' {
  declare module.exports: $Exports<'pnotify/dist/es/PNotifyDesktop'>;
}
declare module 'pnotify/dist/es/PNotifyHistory.js' {
  declare module.exports: $Exports<'pnotify/dist/es/PNotifyHistory'>;
}
declare module 'pnotify/dist/es/PNotifyMobile.js' {
  declare module.exports: $Exports<'pnotify/dist/es/PNotifyMobile'>;
}
declare module 'pnotify/dist/es/PNotifyNonBlock.js' {
  declare module.exports: $Exports<'pnotify/dist/es/PNotifyNonBlock'>;
}
declare module 'pnotify/dist/es/PNotifyReference.js' {
  declare module.exports: $Exports<'pnotify/dist/es/PNotifyReference'>;
}
declare module 'pnotify/dist/es/PNotifyStyleMaterial.js' {
  declare module.exports: $Exports<'pnotify/dist/es/PNotifyStyleMaterial'>;
}
declare module 'pnotify/dist/iife/PNotify.js' {
  declare module.exports: $Exports<'pnotify/dist/iife/PNotify'>;
}
declare module 'pnotify/dist/iife/PNotifyAnimate.js' {
  declare module.exports: $Exports<'pnotify/dist/iife/PNotifyAnimate'>;
}
declare module 'pnotify/dist/iife/PNotifyButtons.js' {
  declare module.exports: $Exports<'pnotify/dist/iife/PNotifyButtons'>;
}
declare module 'pnotify/dist/iife/PNotifyCallbacks.js' {
  declare module.exports: $Exports<'pnotify/dist/iife/PNotifyCallbacks'>;
}
declare module 'pnotify/dist/iife/PNotifyCompat.js' {
  declare module.exports: $Exports<'pnotify/dist/iife/PNotifyCompat'>;
}
declare module 'pnotify/dist/iife/PNotifyConfirm.js' {
  declare module.exports: $Exports<'pnotify/dist/iife/PNotifyConfirm'>;
}
declare module 'pnotify/dist/iife/PNotifyDesktop.js' {
  declare module.exports: $Exports<'pnotify/dist/iife/PNotifyDesktop'>;
}
declare module 'pnotify/dist/iife/PNotifyHistory.js' {
  declare module.exports: $Exports<'pnotify/dist/iife/PNotifyHistory'>;
}
declare module 'pnotify/dist/iife/PNotifyMobile.js' {
  declare module.exports: $Exports<'pnotify/dist/iife/PNotifyMobile'>;
}
declare module 'pnotify/dist/iife/PNotifyNonBlock.js' {
  declare module.exports: $Exports<'pnotify/dist/iife/PNotifyNonBlock'>;
}
declare module 'pnotify/dist/iife/PNotifyReference.js' {
  declare module.exports: $Exports<'pnotify/dist/iife/PNotifyReference'>;
}
declare module 'pnotify/dist/iife/PNotifyStyleMaterial.js' {
  declare module.exports: $Exports<'pnotify/dist/iife/PNotifyStyleMaterial'>;
}
declare module 'pnotify/dist/umd/PNotify.js' {
  declare module.exports: $Exports<'pnotify/dist/umd/PNotify'>;
}
declare module 'pnotify/dist/umd/PNotifyAnimate.js' {
  declare module.exports: $Exports<'pnotify/dist/umd/PNotifyAnimate'>;
}
declare module 'pnotify/dist/umd/PNotifyButtons.js' {
  declare module.exports: $Exports<'pnotify/dist/umd/PNotifyButtons'>;
}
declare module 'pnotify/dist/umd/PNotifyCallbacks.js' {
  declare module.exports: $Exports<'pnotify/dist/umd/PNotifyCallbacks'>;
}
declare module 'pnotify/dist/umd/PNotifyCompat.js' {
  declare module.exports: $Exports<'pnotify/dist/umd/PNotifyCompat'>;
}
declare module 'pnotify/dist/umd/PNotifyConfirm.js' {
  declare module.exports: $Exports<'pnotify/dist/umd/PNotifyConfirm'>;
}
declare module 'pnotify/dist/umd/PNotifyDesktop.js' {
  declare module.exports: $Exports<'pnotify/dist/umd/PNotifyDesktop'>;
}
declare module 'pnotify/dist/umd/PNotifyHistory.js' {
  declare module.exports: $Exports<'pnotify/dist/umd/PNotifyHistory'>;
}
declare module 'pnotify/dist/umd/PNotifyMobile.js' {
  declare module.exports: $Exports<'pnotify/dist/umd/PNotifyMobile'>;
}
declare module 'pnotify/dist/umd/PNotifyNonBlock.js' {
  declare module.exports: $Exports<'pnotify/dist/umd/PNotifyNonBlock'>;
}
declare module 'pnotify/dist/umd/PNotifyReference.js' {
  declare module.exports: $Exports<'pnotify/dist/umd/PNotifyReference'>;
}
declare module 'pnotify/dist/umd/PNotifyStyleMaterial.js' {
  declare module.exports: $Exports<'pnotify/dist/umd/PNotifyStyleMaterial'>;
}
declare module 'pnotify/lib/es/PNotify.js' {
  declare module.exports: $Exports<'pnotify/lib/es/PNotify'>;
}
declare module 'pnotify/lib/es/PNotifyAnimate.js' {
  declare module.exports: $Exports<'pnotify/lib/es/PNotifyAnimate'>;
}
declare module 'pnotify/lib/es/PNotifyButtons.js' {
  declare module.exports: $Exports<'pnotify/lib/es/PNotifyButtons'>;
}
declare module 'pnotify/lib/es/PNotifyCallbacks.js' {
  declare module.exports: $Exports<'pnotify/lib/es/PNotifyCallbacks'>;
}
declare module 'pnotify/lib/es/PNotifyCompat.js' {
  declare module.exports: $Exports<'pnotify/lib/es/PNotifyCompat'>;
}
declare module 'pnotify/lib/es/PNotifyConfirm.js' {
  declare module.exports: $Exports<'pnotify/lib/es/PNotifyConfirm'>;
}
declare module 'pnotify/lib/es/PNotifyDesktop.js' {
  declare module.exports: $Exports<'pnotify/lib/es/PNotifyDesktop'>;
}
declare module 'pnotify/lib/es/PNotifyHistory.js' {
  declare module.exports: $Exports<'pnotify/lib/es/PNotifyHistory'>;
}
declare module 'pnotify/lib/es/PNotifyMobile.js' {
  declare module.exports: $Exports<'pnotify/lib/es/PNotifyMobile'>;
}
declare module 'pnotify/lib/es/PNotifyNonBlock.js' {
  declare module.exports: $Exports<'pnotify/lib/es/PNotifyNonBlock'>;
}
declare module 'pnotify/lib/es/PNotifyReference.js' {
  declare module.exports: $Exports<'pnotify/lib/es/PNotifyReference'>;
}
declare module 'pnotify/lib/es/PNotifyStyleMaterial.js' {
  declare module.exports: $Exports<'pnotify/lib/es/PNotifyStyleMaterial'>;
}
declare module 'pnotify/lib/iife/PNotify.js' {
  declare module.exports: $Exports<'pnotify/lib/iife/PNotify'>;
}
declare module 'pnotify/lib/iife/PNotifyAnimate.js' {
  declare module.exports: $Exports<'pnotify/lib/iife/PNotifyAnimate'>;
}
declare module 'pnotify/lib/iife/PNotifyButtons.js' {
  declare module.exports: $Exports<'pnotify/lib/iife/PNotifyButtons'>;
}
declare module 'pnotify/lib/iife/PNotifyCallbacks.js' {
  declare module.exports: $Exports<'pnotify/lib/iife/PNotifyCallbacks'>;
}
declare module 'pnotify/lib/iife/PNotifyCompat.js' {
  declare module.exports: $Exports<'pnotify/lib/iife/PNotifyCompat'>;
}
declare module 'pnotify/lib/iife/PNotifyConfirm.js' {
  declare module.exports: $Exports<'pnotify/lib/iife/PNotifyConfirm'>;
}
declare module 'pnotify/lib/iife/PNotifyDesktop.js' {
  declare module.exports: $Exports<'pnotify/lib/iife/PNotifyDesktop'>;
}
declare module 'pnotify/lib/iife/PNotifyHistory.js' {
  declare module.exports: $Exports<'pnotify/lib/iife/PNotifyHistory'>;
}
declare module 'pnotify/lib/iife/PNotifyMobile.js' {
  declare module.exports: $Exports<'pnotify/lib/iife/PNotifyMobile'>;
}
declare module 'pnotify/lib/iife/PNotifyNonBlock.js' {
  declare module.exports: $Exports<'pnotify/lib/iife/PNotifyNonBlock'>;
}
declare module 'pnotify/lib/iife/PNotifyReference.js' {
  declare module.exports: $Exports<'pnotify/lib/iife/PNotifyReference'>;
}
declare module 'pnotify/lib/iife/PNotifyStyleMaterial.js' {
  declare module.exports: $Exports<'pnotify/lib/iife/PNotifyStyleMaterial'>;
}
declare module 'pnotify/lib/umd/PNotify.js' {
  declare module.exports: $Exports<'pnotify/lib/umd/PNotify'>;
}
declare module 'pnotify/lib/umd/PNotifyAnimate.js' {
  declare module.exports: $Exports<'pnotify/lib/umd/PNotifyAnimate'>;
}
declare module 'pnotify/lib/umd/PNotifyButtons.js' {
  declare module.exports: $Exports<'pnotify/lib/umd/PNotifyButtons'>;
}
declare module 'pnotify/lib/umd/PNotifyCallbacks.js' {
  declare module.exports: $Exports<'pnotify/lib/umd/PNotifyCallbacks'>;
}
declare module 'pnotify/lib/umd/PNotifyCompat.js' {
  declare module.exports: $Exports<'pnotify/lib/umd/PNotifyCompat'>;
}
declare module 'pnotify/lib/umd/PNotifyConfirm.js' {
  declare module.exports: $Exports<'pnotify/lib/umd/PNotifyConfirm'>;
}
declare module 'pnotify/lib/umd/PNotifyDesktop.js' {
  declare module.exports: $Exports<'pnotify/lib/umd/PNotifyDesktop'>;
}
declare module 'pnotify/lib/umd/PNotifyHistory.js' {
  declare module.exports: $Exports<'pnotify/lib/umd/PNotifyHistory'>;
}
declare module 'pnotify/lib/umd/PNotifyMobile.js' {
  declare module.exports: $Exports<'pnotify/lib/umd/PNotifyMobile'>;
}
declare module 'pnotify/lib/umd/PNotifyNonBlock.js' {
  declare module.exports: $Exports<'pnotify/lib/umd/PNotifyNonBlock'>;
}
declare module 'pnotify/lib/umd/PNotifyReference.js' {
  declare module.exports: $Exports<'pnotify/lib/umd/PNotifyReference'>;
}
declare module 'pnotify/lib/umd/PNotifyStyleMaterial.js' {
  declare module.exports: $Exports<'pnotify/lib/umd/PNotifyStyleMaterial'>;
}
declare module 'pnotify/make.js' {
  declare module.exports: $Exports<'pnotify/make'>;
}
declare module 'pnotify/src/PNotifyCompat.js' {
  declare module.exports: $Exports<'pnotify/src/PNotifyCompat'>;
}
