// flow-typed signature: 584453382f50719e0978fef95f3a5154
// flow-typed version: <<STUB>>/foundation-icons_v^1.0.1/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'foundation-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'foundation-icons' {
  declare module.exports: any;
}
